#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    # colorscheme = "molokai"
    colorscheme = "gruvbox"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = true
    filemanager = "vimfiler"
    #filemanager = "nerdtree"
    bootstrap_before = "bootstrap#before"
    bootstrap_after = "bootstrap#after"

[[custom_plugins]]
name = 'othree/xml.vim'
# note: you need to disable merged feature
merged = 0 

#[[custom_plugins]]
#name = 'tpope/vim-repeat'
## note: you need to disable merged feature
#merged = 0 

#[[custom_plugins]]
#name = 'tpope/vim-surround'
## note: you need to disable merged feature
#merged = 0 

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

# Enable colorschemes 
[[layers]]
name = 'colorscheme'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "denite"

#[[layers]]
#name = "ctrlp"

[[layers]]
name = "debug"

[[layers]]
name = 'lang#sh'

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#perl"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#php"

[[layers]]
name = "lang#dockerfile"
